apiVersion: v1
kind: Service
metadata:
  name: {{ include "jxui.fullname" . }}
  labels:
    {{- include "jxui.labels" . | nindent 4 }}
    {{- with .Values.service.labels }}
    {{ tpl (toYaml .) $ | trim | indent 4 }}
    {{- end }}
  {{- with .Values.service.annotations }}
  annotations: {{- tpl (toYaml .) $ | trim | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.service.type }}
  type: {{ . }}
  {{- end }}
  {{- with .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ . }}
  {{- end }}
  ports:
  - name: http
    port: {{ .Values.service.port }}
    targetPort: http
  selector: {{- include "jxui.labels.selector" . | nindent 4 }}